name: Deploy Application

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Pull Changes
    runs-on: ubuntu-latest
    steps:
      - name: Check for Package changes
        uses: appleboy/ssh-action@master
        id: package_check
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if sudo /usr/bin/id www >/dev/null 2>&1; then
              echo 'user found'

              cd /www/wwwroot/siaji.com
              CHANGES=$(sudo -u www git diff --name-only HEAD origin/main | grep 'package.json' || echo "no_changes")
              # Use proper comparison for string variables
              if [ "$CHANGES" = 'no_changes' ]; then
                  echo "No Changes in package.json"
              else
                  echo "Changes detected, install dependency"
                  whoami
                  pwd
                  echo "========= Handle package"
                  cd /www/wwwroot/siaji.com
                  sudo -u www rm -rf package-lock.json
              fi
            else
              echo 'user not found'
            fi

      - name: Cloning Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            echo "========= Github Action for Pulling Data"
            cd /www/wwwroot/siaji.com
            sudo -u www git checkout release
            sudo -u www git reset --hard
            sudo -u www git pull origin release

      - name: Install package changes
        uses: appleboy/ssh-action@master
        id: package_install
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if sudo /usr/bin/id www >/dev/null 2>&1; then
              echo 'user found'

              cd /www/wwwroot/siaji.com
              CHANGES=$(sudo -u www git diff --name-only HEAD~1 HEAD | grep 'package.json' || echo "no_changes")
              # Use proper comparison for string variables
              if [ "$CHANGES" = 'no_changes' ]; then
                  echo "No Changes in package.json"
              else
                  echo "Changes detected, install dependency"
                  whoami
                  pwd
                  echo "========= Handle package"
                  cd /www/wwwroot/siaji.com
                  sudo -u www npm install
              fi
            else
              echo 'user not found'
            fi

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Handle submodule and generate file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            cd /www/wwwroot/siaji.com
            echo "========= Clear Rebuild Submodule"
            sudo -u www git submodule init
            sudo -u www git submodule update
            echo "========= Clear Rebuild Hexo"
            sudo -u www npm run build
