name: Deploy Application

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Pull Changes
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            echo "========= Github Action for Pulling Data"
            cd /www/wwwroot/siaji.com
            sudo -u www git checkout release
            sudo -u www git reset --hard
            sudo -u www git pull origin release

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Handle submodule and generate file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            cd /www/wwwroot/siaji.com
            echo "========= Clear Rebuild Submodule"
            sudo -u www git submodule init
            sudo -u www git submodule update
            echo "========= Clear Rebuild Hexo"
            sudo -u www npm run build
